name       : python-pytest-httpserver
version    : 1.0.4
release    : 6
source     :
    - https://files.pythonhosted.org/packages/source/p/pytest_httpserver/pytest_httpserver-1.0.4.tar.gz : 6de464ba5f74628d6182ebbdcb56783edf2c9b0caf598dc35c11f014f24a3f0d
homepage   : https://github.com/csernazs/pytest-httpserver
license    : MIT
component  : programming.python
summary    : pytest-httpserver is a httpserver for pytest
description: |
    This library is designed to help to test http clients without contacting the real http server. In other words, it is a fake http server which is accessible via localhost can be started with the pre-defined expected http requests and their responses.
builddeps  :
    - python-pytest
    - python-requests
    - python-werkzeug
rundeps    :
    - python-werkzeug
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
