name       : python-pytest-httpserver
version    : 1.0.8
release    : 8
source     :
    - https://github.com/csernazs/pytest-httpserver/archive/refs/tags/1.0.8.tar.gz : d25a765e660f252029738392cff49dd3b2d6e5070ac81c7fb794ae6eac93ef76
homepage   : https://github.com/csernazs/pytest-httpserver
license    : MIT
component  : programming.python
summary    : pytest-httpserver is a httpserver for pytest
description: |
    This library is designed to help to test http clients without contacting the real http server. In other words, it is a fake http server which is accessible via localhost can be started with the pre-defined expected http requests and their responses.
builddeps  :
    - python-build
    - python-installer
    - python-poetry
    - python-pytest   # check
    - python-toml     # check
    - python-werkzeug # check
rundeps    :
    - python-werkzeug
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest -v
